name: stdetector
description: stress detector


publish_to: 'none'

version: 1.2.3+5

environment:
  sdk: '>=3.0.3 <4.0.0'




dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bluetooth_serial: ^0.4.0
  syncfusion_flutter_charts: ^20.1.50
  path_provider: ^2.0.10
  csv: ^5.0.1
  share_plus: ^4.0.5
  sqflite: any
  fluttertoast: ^8.0.9
  flutter_toastr: ^1.0.3
  http: ^1.0.0
  shared_preferences: ^2.1.2
  permission_handler: ^11.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1



  flutter_lints: ^2.0.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  #flutter pub run flutter_launcher_icons


flutter:


  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/icon.png




























